[build]
  command="ng build"
  publish="dist/angular-quickstart"

[[redirects]]
  from = "/builder/*"
  to = "https://fluffy-manatee-151860.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
